version: '3'

services:

  react:
    image: node:16
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      REACT_APP_NODE_URL: $NODE_URL
    command: ['npm','start']
    ports:
      - $REACT_PORT:3000

  node:
    image: node:16
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ['npm','run','start']
    ports:
      - 8000:8000
    environment:
      MONGO_USERNAME: $MONGOUSER
      MONGO_PASSWORD: $MONGOPASSWORD
    
  mongo:
    image: mongo:6
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGOUSER
      MONGO_INITDB_ROOT_PASSWORD: $MONGOPASSWORD